name: Run License Tests
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  license_tests:
    uses: neongeckocom/.github/.github/workflows/license_tests.yml@FEAT_ConfigureLicenseTests
    with:
      packages-exclude: '^(neon-metrics-service|tqdm).*'